USE ROLE SYSADMIN;
USE SCHEMA PLATFORM_DB.PLATFORM_APP;
CREATE OR REPLACE sequence ORGANIZATION_USAGE_load_run_SEQ start = 1 increment = 1;

CREATE OR REPLACE table PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS
(LoadName varchar ,Datekey varchar ,HashColumnKey varchar ,Active  INT default 0);


INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('WAREHOUSE_METERING_HISTORY','START_TIME','ORGANIZATION_NAME,ACCOUNT_NAME,REGION,SERVICE_TYPE,WAREHOUSE_ID,START_TIME');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('METERING_DAILY_HISTORY','USAGE_DATE','SERVICE_TYPE,ORGANIZATION_NAME, ACCOUNT_NAME,USAGE_DATE,REGION');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('DATA_TRANSFER_DAILY_HISTORY','USAGE_DATE','SERVICE_TYPE,ORGANIZATION_NAME, ACCOUNT_NAME,USAGE_DATE,REGION');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('USAGE_IN_CURRENCY_DAILY','USAGE_DATE','ORGANIZATION_NAME,CONTRACT_NUMBER,ACCOUNT_NAME,REGION,USAGE_DATE,USAGE_TYPE');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('STORAGE_DAILY_HISTORY','USAGE_DATE','SERVICE_TYPE,ORGANIZATION_NAME,ACCOUNT_NAME,REGION');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('REMAINING_BALANCE_DAILY','DATE','ORGANIZATION_NAME,CONTRACT_NUMBER,DATE,CURRENCY');


INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS  (LoadName,Datekey,HashColumnKey)
VALUES('RATE_SHEET_DAILY','DATE','ORGANIZATION_NAME,CONTRACT_NUMBER,DATE,ACCOUNT_NAME,REGION,SERVICE_TYPE');

INSERT INTO PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_LOAD_PROCESS (LoadName,Datekey,HashColumnKey)
VALUES('CONTRACT_ITEMS','START_DATE','ORGANIZATION_NAME,CONTRACT_NUMBER,START_DATE,CONTRACT_ITEM,CONTRACT_MODIFIED_DATE');


Update "PLATFORM_DB"."PLATFORM_APP"."ORGANIZATION_USAGE_LOAD_PROCESS" SET ACTIVE=1;

CREATE OR REPLACE TABLE ORGANIZATION_USAGE_LOAD_RUN (
	RUN_ID NUMBER(38,0) DEFAULT PLATFORM_DB.PLATFORM_APP.ORGANIZATION_USAGE_load_run_SEQ.NEXTVAL COMMENT 'SYSTEM GENERATED SEQUENCE',
    ORGANIZATION_USAGE_LOAD VARCHAR,
    JOB_DESCRIPTION VARIANT,
    JOB_STARTED_TS TIMESTAMP_NTZ(9),
	JOB_COMPLETED_TS TIMESTAMP_NTZ(9)
);